### ISSUE TITLE
Bug: current chapter wrong while in landscape mode

### ISSUE THREAD

**Issue by bust4cap** [VandersonQk/KuroReaderReleases#11]
Chapters work fine when in portrait mode, but when you switch to landscape mode, so you have 2 images next to each other, it seems to count both images together as only one page, so the chapter count is wrong.
example:
you have a chapter every 20 pages. in portrait mode this is detected correctly.
in landscape mode, the chapter only changes every 40 pages.
this only affects the displayed chapter name. switching the chapter via the table of contents still goes to the correct page

**Comment by VandersonQk** [comment]
Fixed on version 1.6.0 ([Download in releases](https://github.com/VandersonQk/KuroReaderReleases/releases/latest))
