### ISSUE TITLE
"All Books" issue and other enhancements

### ISSUE THREAD

**Issue by PhilipElom** [VandersonQk/KuroReaderReleases#14]
In the All Books category, not all books have their Author's name showing despite that metadatum being filled out. And speaking of the Home Page, it would be nice to see it more detailed displaying the file name and directory, the actual book and other metadata (like Notes, Summary, Tags). It would be nice not to click each book to see this. Thank you for your work.

**Comment by VandersonQk** [comment]
I misunderstood the issue you reported via email, I didn't realize you were talking about the names of the artists/staff in the books, I thought it was about the main list of all the authors. I've fixed that, and now all authors are shown. (check the screenshots below, is that what you're talking about?)

As for showing more details, it's simple in the coding, but the UI part... there's not enough room. A simple example is the synopsis, on a regular smartphone (1080p screen, system set to small font size), only two lines of the synopsis would be visible in a comic with a two-line title. Using the system set to a large font size, there is no room at all. And I'm not going to increase the size of the items, it's already too big...

Examples:
- Small font size
![Small font size](https://github.com/VandersonQk/KuroReaderReleases/assets/7416219/94951407-085e-47ab-850d-1cc301a8b0fc)

- Big font size
![Big font size](https://github.com/VandersonQk/KuroReaderReleases/assets/7416219/58f063e7-e7f3-4312-b161-77708e21ecc7)

**Comment by PhilipElom** [comment]
It doesn't really matter if the entire synopsis shows. At least, that
little tidbit could pique or satiate a reader's curiosity as regards the
comic he's about to read.

**Comment by PhilipElom** [comment]
1. I wouldn't mind if the UI looked just like the first screenshot with the
smaller font. I would love it, in fact (with the file path included). It's
just a matter of making the thumbnail larger and the fonts smaller.
2. When I spoke about the Author issue, I meant that not all the books had
their Author's name being displayed in the All Books category despite the
metadata being filled out.

**Comment by VandersonQk** [comment]
> The second doesn't after I scroll down bit and
then back up.

I can't see the screenshots because you replied by email, but I know the problem. I found and fixed it when I was working on the code to merge all the author names.

**Comment by PhilipElom** [comment]
But why aren't the changes reflecting on my device? Do I need re-install
the app?

**Comment by VandersonQk** [comment]
> But why aren't the changes reflecting on my device? Do I need re-install
the app?

The fix will be in the next app update, but no date has been set yet.

**Comment by VandersonQk** [comment]
Fixed the issues with the author's name and added the option to show the synopsis in expanded list mode. The other book details will not be added mostly because there is no room for them, and adding more items would make the list too overloaded.

**Comment by VandersonQk** [comment]
> So when can we expect the new update?

The new update is already available [here](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.1) and on the Play Store.  In the app, open the side menu and click on About ("i" icon) and then on "Check update".

**Comment by PhilipElom** [comment]
Love, love, LOVE the update. It was nice seeing the changes made. But I
noticed that the main menu can't seem to differentiate Volume, Issue and
Count (1st screenshot). And in the Books screen, it doesn't show the Volume
number (2nd number). I would be really grateful if you could rectify these
issues.

**Comment by VandersonQk** [comment]
> But I noticed that the main menu can't seem to differentiate Volume, Issue and Count (1st screenshot). 

I can't see your screenshots because Github doesn't allow attachments via email reply. Please send the screenshots to apps @ kurotoshiro.dev or via comment directly in the issue.(#14)

**Comment by PhilipElom** [comment]
Love, love, LOVE the update. It was nice seeing the changes made. But I noticed that the main menu can't seem to differentiate Volume, Issue and Count (1st screenshot). And in the Books screen, it doesn't show the Volume number (2nd number). I would be really grateful if you could rectify these issues. Also, will anything be done about the Table of Contents. It seems not to be useful except when I'm reading comics that I myself created by combining different comic books together with the Comic Rack pc app
![Screenshot_20240801-182034](https://github.com/user-attachments/assets/ac58b0d1-f98f-4dd5-9c48-394f7c514cf3)
![Screenshot_20240801-182432](https://github.com/user-attachments/assets/80a2d9ae-5ce2-43e4-946a-444d1ecc1ad8)

**Comment by PhilipElom** [comment]
In the first image, the actual metadata for both books are Ultimates Vol. 2, Issue 1 and Ultimates Vol. 2, issue 2. Not what's shown.
In the second screenshot, the actual metadata is supposed to be Invincible TPB 17, 18 and 19 for all three books respectively. The volume numbers are missing here.

**Comment by VandersonQk** [comment]
I'll take a look and add/fix the support

**Comment by PhilipElom** [comment]
OK. Thanks for your assistance. I really appreciate... Oh, and one other
thing, if it's not too much. It's something I noticed about the newer
updates: if I leave the app for too long, it shows file error or rar error
when I open the app from my recently opened apps window, an issue the older
model like the 15.6 model didn't have...

**Comment by PhilipElom** [comment]
Good day to you. Sorry for the disturbance but I would like request an enhancement: the scanner doesn't pick up new books added or old books move to another subfolder or books with recently added metadata. It sometimes takes minutes or even an hour for it to update. It would be nice if this was rectified by the next update. Thank you.

**Comment by PhilipElom** [comment]
The error issue after inactivity hasn't been solved, sir... 
![Screenshot_20241020-130807](https://github.com/user-attachments/assets/ddbb86e7-e559-40b6-b969-5fd416650bdb)

**Comment by VandersonQk** [comment]
Now it's really fixed (I hope): [version 1.6.2](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.2-hotfix)

**Comment by PhilipElom** [comment]
It works now... But as a result, long-pressing to move to the next book in
a series no longer works.

**Comment by PhilipElom** [comment]
And also, I would like to know what those 3 buttons on the bottom left of
the 'Edit Metadata' page do.

**Comment by VandersonQk** [comment]
> It works now... But as a result, long-pressing to move to the next book in a series no longer works.

Firstly, I'll explain why you got the error before: it simply happens because when you minimize the app, your smartphone is "killing" the app to free up RAM. Usually this doesn't happen because Kuro Reader uses very little RAM (150mb~300mb), but there are settings in android that can force the app to close to save battery (such as clearing memory when you lock the screen). After the app is "killed" some information remains in the RAM, specifically the book ID, with which it is possible to retrieve the last book opened, but not the list of books. So there's no way to navigate between books.

> 3 buttons on the bottom left of the 'Edit Metadata' page

1 - Auto Generate: use the filename to fill in some basic information (series name, volume, chapter)
2 - Remove properties: delete all book details in the editor
3 - Generate from web: use a myanimelist manga page to fill in the book details

*Long press on the button to see the name of the associated function

**Comment by PhilipElom** [comment]
Thanks for the info. So there's nothing that can be done for now as regards
the first issue? Btw that last button... Why use myanimelist? Why not
something like Comic Vine which is more relevant?
