### ISSUE TITLE
Smol Feature Request (remember scroll position)

### ISSUE THREAD

**Issue by throwaway1245725** [VandersonQk/KuroReaderReleases#16]
Hey there, I have around 30,000 books in my library, and whenever i'm scrolling through them in the Library or Files section, and i navigate into a folder/author/sorted list and back, it resets to the top of the list instead of remembering the scroll position. It would be nice if it could remember the scroll position and stay there once we navigate back up.

Thanks!

**Comment by VandersonQk** [comment]
Added in the [version 1.6.2](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.2-hotfix), it can be enabled in the settings. ("Settings"-> "Files" tab -> "Remember position in the file list")

**Comment by throwaway1245725** [comment]
> Added in the [version 1.6.2](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.2-hotfix), it can be enabled in the settings. ("Settings"-> "Files" tab -> "Remember position in the file list")

Thanks!
