### ISSUE TITLE
Folder progress and status

### ISSUE THREAD

**Issue by flesh127** [VandersonQk/KuroReaderReleases#19]
Your app is the best manga library there is on android. I even bought a pro version because of how much i appreciate the details.

What I think would make experience better js: progress bars on folders AND subfolders. Status may be automatic based on progress bar.

**Comment by VandersonQk** [comment]
Added in the [version 1.6.2](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.2-hotfix), it can be enabled/disabled in the customization menu
