### ISSUE TITLE
Top folder bug

### ISSUE THREAD

**Issue by flesh127** [VandersonQk/KuroReaderReleases#20]
Number of books is shown incorrectly on top folder. Might be because of subfolders

![Screenshot_20240814_031122_Kuro Reader+ Pro](https://github.com/user-attachments/assets/963beb55-f8c7-4adb-ac5b-2036b3c1a972)
![Screenshot_20240814_031131_Kuro Reader+ Pro](https://github.com/user-attachments/assets/305c6ecc-f177-4b5c-98e7-e362913e198a)

**Comment by VandersonQk** [comment]
Fixed in [version 1.6.2](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.2-hotfix)
