### ISSUE TITLE
中文排序 (Chinese name sorting)

### ISSUE THREAD

**Issue by crazywheel** [VandersonQk/KuroReaderReleases#22]
很不错的app，已支持pro+，有几个小问题，如下
1.是否可以优化一下中文排序，目前中文排序很乱。
2.最新1.6.1，书架的样式比之前版本少了几个样式。
3.增加双页裁剪成单页的功能。

**Comment by VandersonQk** [comment]
Update:

> 1.是否可以优化一下中文排序，目前中文排序很乱。

>3.增加双页裁剪成单页的功能。

Added in [version 1.6.2](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.2-hotfix):
- Custom sorting is now available in the settings, enabled by default. ("Settings"-> "Interface" tab -> "Regional filename sorting")
- Double page splitting is now available in the setting, enabled by default. ("Settings"-> "Reader" tab -> "Split double page visualization")
