### ISSUE TITLE
app crash when entering backup and restore with dark mode/system on dark mode theme

### ISSUE THREAD

**Issue by Kitsune2431** [VandersonQk/KuroReaderReleases#25]
As title. App is crashing right after entering backup & restore if u have dark/system on dark mode theme. Works fine with light theme. My phone is samsung a52s 5g android 14 one ui 6.1.

**Comment by VandersonQk** [comment]
Fixed on [version 1.6.2](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.2-hotfix)
