### ISSUE TITLE
[BUG] Mapping comic gets stuck at 0 or 5% when pages in comicinfo arent fully populated

### ISSUE THREAD

**Issue by bust4cap** [VandersonQk/KuroReaderReleases#30]
**App details**
- Version: 1.6.1
- Type: Pro
- Distribuition: PlayStore
- File access mode (setting): Full

**Smartphone/Tablet:**
 - Android Version: 12
 - Device: Lenovo Tab M10 (3rd Gen)

**Describe the bug**
When the pages section in a comicinfo.xml doesnt list every single page but only those that contain chapters for example, mapping comic gets stuck at 0 or 5% and times out after a few seconds. it may also lead to a software crash

**To Reproduce**
1. Have a cbz including a comicinfo.xml that only has those pages listed that contain chapter info instead of every single page
2. When opening the cbz to read it (either with auto map comic enabled or when putting the tablet in landscape mode when auto map comic isnt enabled) mapping comic gets stuck at 0 or 5% and times out after a few seconds, therefore never finishing and two page view not working

**Comment by VandersonQk** [comment]
Please try the new update. To fix #29, I rewrote the code for encoding the xml file containing the mapping, and after that I couldn't reproduce this bug anymore. I can't confirm that it's fixed, so please give me an update after testing.

**Comment by bust4cap** [comment]
yup, seems to be fixed on my end, too
