### ISSUE TITLE
[BUG] The order ID was not found, please check the ID and try again.

### ISSUE THREAD

**Issue by Skilledcamman** [VandersonQk/KuroReaderReleases#34]
I got the code in my email but when I try it on the website it doesn't work and gives error
The order ID was not found, please check the ID and try again.

![image](https://github.com/user-attachments/assets/c0d7b041-bd21-4011-b9bd-dfde21c036e5)

**Comment by bust4cap** [comment]
how long ago did you purchase it?

**Comment by VandersonQk** [comment]
@Skilledcamman How long ago have you bought the app? Currently, only purchases up to October 31st are registered.

For new purchases, it can take up to 45 days for them to be registered "automatically", as Google releases the purchase report for a month on the 15th of the following month. (e.g: all purchases made in November will be registered on December 15th)

If that's your case, click on the “Request registration” button on the same page where you see the error, and your email app will open and automatically fill in some information, after which all you have to do is send the email.

Sadly, there is no way for our system to connect to Google's to track new purchases, so this process still has to be done manually. So the whole process can take some time, but on a business day the id will be registered the same day.

**Comment by Skilledcamman** [comment]
I bought it just yesterday, rn the play store app is working for me, any
reason why I need to use the github APK? since the playstore version works.

**Comment by Skilledcamman** [comment]
Ok I get registered, after contacting via email.

**Comment by VandersonQk** [comment]
> I bought it just yesterday, rn the play store app is working for me, any reason why I need to use the github APK? since the playstore version works.

Sorry, I didn't see your comment before. I know it's a bit late, but to answer your question, you don't need to use the APK file. It's just an alternative version to use on devices without Play Store (like Huawei phones).

**Comment by Skilledcamman** [comment]
ahhh, by reading the github I thought the app was banned on play store.
