### ISSUE TITLE
[Request] One finger zoom

### ISSUE THREAD

**Issue by source124** [VandersonQk/KuroReaderReleases#39]
**What needs will the feature fulfil? Please describe.**

For one-handed use.

**Describe the solution you'd like**

Tap twice but don't release the second tap. This activates zooming. Slide up and down to zoom in/out.

**Additional context (optional)**
See an ancient app for an implementation: https://github.com/sketchpunk/opencomicreader (You can get the last APK here: https://apkcombo.com/open-comic-reader/com.sketchpunk.ocomicreader/)

**Comment by VandersonQk** [comment]
I believe the app already has this zoom function:

https://github.com/user-attachments/assets/3715ff35-79b2-404f-b67d-ee7b2277efe5

**Comment by source124** [comment]
You are right. I don't know how I missed it!

It's too fast though. A small swipe causes massive zoom. I'd dial it back a bit.

Thanks!
