### ISSUE TITLE
google play pro version

### ISSUE THREAD

**Issue by hackbot1337** [VandersonQk/KuroReaderReleases#5]
so i bought the pro version on the playstore. i tried to install the apk on a new tablet that i bought tied to the same account and it wont let me install the app.

**Comment by VandersonQk** [comment]
What exactly is the problem you are having? The apk does not install at all? Or it does install and shows errors / crash?

**Comment by hackbot1337** [comment]
it crashed but i resolved that issue by resetting my tablet. now i cant find the code in my purchase history and i dont keep emails for longer than 3 months. what do i do. i have the original pro install on one of my other tablets.

**Comment by VandersonQk** [comment]
Okay. Since this is related to personal data, could you contact me by email? I can check your purchase details in the Play Store system using your email address. (email: apps@kurotoshiro.dev)
