### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Maybeyok** [VandersonQk/KuroReaderReleases#7]
When the library folder is hidden, the browse history should also be hidden！

**Comment by Maybeyok** [comment]
> When the library folder is hidden, the browse history should also be hidden！
The latest version still doesn't fix the problem.😭😭

**Comment by VandersonQk** [comment]
Added in [version 1.6.2](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.2-hotfix)
