### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Maybeyok** [VandersonQk/KuroReaderReleases#9]
Some comics in CBZ format cannot change  the book cover.![Screenshot_2024-04-09-10-05-46-691_br.com.kurotoshiro.kuro_reader_pro.jpg](https://github.com/VandersonQk/KuroReaderReleases/assets/127712226/5e526110-d781-43a0-9678-3414a51ea2e2)

![Screenshot_2024-04-09-10-05-49-353_br.com.kurotoshiro.kuro_reader_pro.jpg](https://github.com/VandersonQk/KuroReaderReleases/assets/127712226/67840f61-5f4d-4a46-8565-e3aebfd442d4)

![Screenshot_2024-04-09-10-06-31-909_br.com.kurotoshiro.kuro_reader_pro.jpg](https://github.com/VandersonQk/KuroReaderReleases/assets/127712226/459e6159-5732-40f0-b0fb-b5112ad5ccb0)
Sometimes when I refresh the library , the changed cover is restored to the original, which is not what I want.

**Comment by VandersonQk** [comment]
It took a long time, but I believe I found the bug that's in your screenshot. I just need a confirmation from you, are the file in a SAF folder ("Local (SAF)") ? You can check it in the "Library folders" option (Settings -> Library tab -> Library Folders)

![screnshot_folder](https://github.com/VandersonQk/KuroReaderReleases/assets/7416219/6162da55-5395-4e97-9c7c-e0a71491a1ef)


But I couldn't find the second issue, Kuro Reader only deletes thumbnails when you remove the comic from the library. When it refreshes the library, it only replaces/updates the thumbnail if the file has changed (more specifically if the file size changes). Maybe that's what's happening.

**Comment by Maybeyok** [comment]
I just reinstalled the software and followed your instructions, and now I can change the cover again！

**Comment by Maybeyok** [comment]
> It took a long time, but I believe I found the bug that's in your screenshot. I just need a confirmation from you, are the file in a SAF folder ("Local (SAF)") ? You can check it in the "Library folders" option (Settings -> Library tab -> Library Folders)
> 
> ![screnshot_folder](https://github.com/VandersonQk/KuroReaderReleases/assets/7416219/6162da55-5395-4e97-9c7c-e0a71491a1ef)
> 
> 
> But I couldn't find the second issue, Kuro Reader only deletes thumbnails when you remove the comic from the library. When it refreshes the library, it only replaces/updates the thumbnail if the file has changed (more specifically if the file size changes). Maybe that's what's happening. 

I just synchronized the stacks, and the changed cover is back to the original.
Let me repeat what I just did. First of all, I changed the title of another comic in the file manager. I entered the software and clicked Maintenance first.I saw that the name of the comic I had changed was not displayed properly in the software, so I clicked Start Full Synchronization.But the modified cover is restored to its original state.
